AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway integrated with Lambda

Parameters:
  LambdaFunctionArn:
    Type: String
    Description: ARN of the Lambda function

Resources:
  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SimpleRestAPI

  RootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - MyRestApi
          - RootResourceId
      PathPart: hello
      RestApiId: !Ref MyRestApi

  GetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyRestApi
      ResourceId: !Ref RootResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: GetMethod
    Properties:
      RestApiId: !Ref MyRestApi
      StageName: prod

  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyRestApi}/*/*/*
