name: Deploy Lambda via CloudFormation

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload Lambda ZIP to S3
      run: |
        zip lambda.zip lambda/app.py
        aws s3 cp lambda.zip s3://my-lambda-bucket-1234-sawan/lambda.zip

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name simple-lambda-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            LambdaS3Bucket=my-lambda-bucket-1234-sawan \
            LambdaS3Key=lambda.zip
